# Build from AlmaLinux 9 (current 9.7)
FROM almalinux:9

# Install EPEL for ROOT and other packages
RUN dnf install -y epel-release && \
    dnf config-manager --set-enabled crb && \
    dnf update -y

# Install pre-reqs
RUN dnf groupinstall -y "Development Tools" && \
    dnf install -y --allowerasing \
    doxygen \
    emacs \
    ffmpeg-free \
    ffmpeg-free-devel \
    gsl \
    gsl-devel \
    hdf5 \
    hdf5-devel \
    less \
    boost-devel \
    eigen3-devel \
    libXpm-devel \
    openmpi \
    openmpi-devel \
    rsync \
    swig \
    valgrind \
    git \
    vim \
    cmake \
    wget \
    curl \
    tcl \
    tcl-devel \
    libXft-devel \
    libXext-devel \
    fftw-devel \
    zlib-devel \
    python3 \
    python3-pip \
    python3-devel \
    root \
    libarchive \
    python3-root \
    root-notebook \
    && dnf clean all

ENV CMAKE_POLICY_VERSION_MINIMUM=3.5
ENV PIP_BREAK_SYSTEM_PACKAGES=1

# Ensure ROOT environment variables on PATH
ENV ROOTSYS="/usr/lib64/root"
ENV ROOT_INCLUDE_PATH="/usr/include/root"
ENV CMAKE_PREFIX_PATH="${ROOTSYS}/cmake:${CMAKE_PREFIX_PATH}"
ENV PATH="${ROOTSYS}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${ROOTSYS}/lib64:${ROOTSYS}/lib:${LD_LIBRARY_PATH}"
ENV PYTHONPATH="${ROOTSYS}/lib64:${ROOTSYS}/lib:${PYTHONPATH}"

# Ensure OpenMPI tools on PATH
ENV OPENMPI_DIR="/usr/lib64/openmpi"
ENV PATH="${OPENMPI_DIR}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${OPENMPI_DIR}/lib:${LD_LIBRARY_PATH}"

# Install additional useful python packages
RUN pip3 install --upgrade pip \
    && pip3 install --no-cache-dir --upgrade --ignore-installed "packaging>=23.0" \
    && pip3 install --no-cache-dir \
    emcee==2.2.1 \
    h5py \
    hic \
    hsluv \
    jupyter \
    matplotlib \
    nbdime \
    numpy \
    pandas \
    pathlib \
    ptemcee \
    pyhepmc \
    pyyaml \
    scikit-learn \
    scipy \
    seaborn \
    tqdm

# Symlink python
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install LHAPDF 6.5.5 in /usr/local
RUN wget --progress=dot:giga --tries=5 --waitretry=5 --timeout=30 \
      -O LHAPDF-6.5.5.tar.gz https://lhapdf.hepforge.org/downloads/LHAPDF-6.5.5.tar.gz && \
    sha256sum LHAPDF-6.5.5.tar.gz && \
    bsdtar -xzf LHAPDF-6.5.5.tar.gz && \
    cd LHAPDF-6.5.5 && \
    ./configure --prefix=/usr && make && make install && \
    cd .. && rm -rf LHAPDF-6.5.5.tar.gz LHAPDF-6.5.5

ENV LHAPATH='/home/jetscape-user/.local/share/LHAPDF'

# Install HepMC 3.2.6
RUN curl -SLf --progress-bar --retry 5 --retry-delay 5 --max-time 600 "http://hepmc.web.cern.ch/hepmc/releases/HepMC3-3.2.6.tar.gz" | tar -xvzC /usr/local \
    && cd /usr/local \
    && mkdir hepmc3-build \
    && cd hepmc3-build \
    && cmake ../HepMC3-3.2.6 -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=lib -DHEPMC3_ENABLE_ROOTIO=ON -DHEPMC3_BUILD_EXAMPLES=ON -DROOT_DIR=${ROOTSYS} -DCMAKE_CXX_STANDARD=17 -DHEPMC3_CXX_STANDARD=17 \
    && make -j8 install \
    && rm -r /usr/local/hepmc3-build

ENV LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"

# Install Pythia8 with HepMC3-3.2.6 (that is needed by SMASH)
ARG pythiaV="8315"
RUN curl -SLkf --progress-bar --retry 5 --retry-delay 5 --max-time 600 "http://pythia.org/download/pythia83/pythia${pythiaV}.tgz" \
    | tar -xvzC /usr/local \
    && cd /usr/local/pythia${pythiaV} \
    && ./configure --enable-shared --prefix=/usr/local/ --with-hepmc3=/usr/local/HepMC3-3.2.6 --with-lhapdf6 \
    && make -j8 \
    && make -j8 install

# Environment setup
ARG username=jetscape-user
ENV JETSCAPE_DIR="/home/${username}/X-SCAPE"
ENV SMASH_DIR="${JETSCAPE_DIR}/external_packages/smash/smash_code"
ENV EIGEN3_ROOT /usr/include/eigen3
ENV PYTHIA8DIR /usr/local/
ENV PYTHIA8 /usr/local/
ENV PYTHIA8_ROOT_DIR /usr/local/
ENV PATH $PATH:$PYTHIA8DIR/bin

# Environment modules
RUN curl -SLkf --progress-bar --retry 5 --retry-delay 5 --max-time 600 "https://sourceforge.net/projects/modules/files/Modules/modules-4.5.1/modules-4.5.1.tar.gz" \
    | tar -xvzC /usr/local \
    && cd /usr/local/modules-4.5.1 \
    && ./configure --prefix=/usr/local --modulefilesdir=/heppy/modules \
    && make -j8 \
    && make -j8 install

# User setup
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd -g ${USER_GID} ${username} \
    && useradd --create-home --home-dir /home/${username} -u ${USER_UID} -g ${USER_GID} ${username}

# Clone X-SCAPE
RUN cd /home/${username} \
    && git clone https://github.com/JETSCAPE/X-SCAPE.git

# Install External Packages
RUN cd /home/${username}/X-SCAPE/external_packages \
    && ./get_music.sh \
    && ./get_iSS.sh \
    && ./get_freestream-milne.sh \
    && ./get_lbtTab.sh \
    && ./get_ipglasma.sh \
    && ./get_smash.sh \
    && ./get_3dglauber.sh \
    && cd /home/${username}/X-SCAPE \
    && mkdir build

# Build X-SCAPE
RUN cd /home/${username}/X-SCAPE/build \
    && cmake .. -DUSE_ROOT=ON -DUSE_3DGlauber=ON -DUSE_MUSIC=ON -DUSE_ISS=ON -DUSE_FREESTREAM=ON -DUSE_SMASH=ON -DUSE_IPGLASMA=ON \
    && make -j4

USER ${username}
ENV HOME /home/${username}
WORKDIR ${HOME}

ENTRYPOINT /bin/bash
