name: docker-build-multiarch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'input for docker version'
        required: true
        type: string
      name:
        description: 'input for container name'
        required: true
        type: string
      path:
        description: 'input to Dockerfile within docker/ folder such as: base/Dockerfile.base'
        required: true
        type: string

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push 
        uses: docker/build-push-action@v3
        with:
          file: ./docker/${{ inputs.path }}
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.name }}:${{ inputs.version }}
